### ISSUE TITLE
create config file based set of default users

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-glauth#5]
For testing we should supply a default config that contains the known demo users

**Comment by butonic** [comment]
fixed by https://github.com/owncloud/ocis-glauth/pull/6, superseeded by https://github.com/owncloud/ocis-glauth/pull/9

**Comment by micbar** [comment]
Closing, needs different approach.

**Comment by butonic** [comment]
superseded by https://github.com/owncloud/ocis-glauth/issues/13

for demoing hard coded users are good enough. for any real deployment the accounts service needs to be used anyway.
